apiVersion: v1
kind: Service
metadata:
  name: scenario-02-service
  namespace: test-scenerios
  labels:
    scenario: "02-api-latency-n-plus-one"
spec:
  type: LoadBalancer
  selector:
    app: scenario-02
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
